# About Dataset

The dataset contains EEG signals from 11 subjects with labels of alert and drowsy. It can be opened with Matlab. We extracted the data for our own research purpose from another public dataset:

Cao, Z., et al., Multi-channel EEG recordings during a sustained-attention driving task. Scientific data, 2019. 6(1): p. 1-8.

If you find the dataset useful, please give credits to their works.

The details on how the data were extracted are described in our paper:

"Jian Cui, Zirui Lan, Yisi Liu, Ruilin Li, Fan Li, Olga Sourina, Wolfgang Müller-Wittig, A Compact and Interpretable Convolutional Neural Network for Cross-Subject Driver Drowsiness Detection from Single-Channel EEG, Methods, 2021, ISSN 1046-2023, https://doi.org/10.1016/j.ymeth.2021.04.017."

The codes of the paper above are accessible from:

https://github.com/cuijiancorbin/A-Compact-and-Interpretable-Convolutional-Neural-Network-for-Single-Channel-EEG

The data file contains 3 variables and they are EEGsample, substate and subindex.

"EEGsample" contains 2022 EEG samples of size 20x384 from 11 subjects. Each sample is a 3s EEG data with 128Hz from 30 EEG channels.
"subindex" is an array of 2022x1. It contains the subject indexes from 1-11 corresponding to each EEG sample.
"substate" is an array of 2022x1. It contains the labels of the samples. 0 corresponds to the alert state and 1 correspond to the drowsy state.

The unbalanced version of this dataset is accessible from:
https://figshare.com/articles/dataset/EEG_driver_drowsiness_dataset_unbalanced_/16586957

# Importing Libraires

In [1]:
import scipy.io
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.io import loadmat
from tabulate import tabulate
import matplotlib.pyplot as plt

# Loading Dataset

In [2]:
file_path = 'EEG driver drowsiness dataset.mat'
mat_data = scipy.io.loadmat(file_path)

In [3]:
print(mat_data)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu Dec 12 16:15:31 2019', '__version__': '1.0', '__globals__': [], 'EEGsample': array([[[ 4.08097622e+00,  5.36373657e+00,  2.16892286e+00, ...,
         -2.43467111e+00, -1.08033326e+01, -4.06570287e+00],
        [ 3.78602291e+00,  6.18806022e+00,  1.72710622e+00, ...,
         -2.23788269e+00, -1.08040545e+01, -3.16985550e+00],
        [ 8.34680437e+00,  8.69160090e+00, -1.09056499e-02, ...,
          2.30521997e+00, -1.33921422e+01, -5.27739673e+00],
        ...,
        [ 1.52884814e+00,  7.93795880e-01, -1.45126572e+00, ...,
         -1.22710349e+00, -5.26310889e+00, -1.22684549e+00],
        [-1.19949821e+00, -1.54496214e+00, -4.31985930e+00, ...,
         -5.32550694e+00, -5.48814272e+00, -1.57636907e+00],
        [ 1.59400945e+00,  1.90051435e+00, -4.64426331e+00, ...,
         -3.48251971e+00, -2.09547756e+00,  4.01980667e+00]],

       [[ 5.10435476e+00,  2.66309990e-01,  3.92736106e+00, ...,
         -2.43175735e+00, -5.35540437e+00, -8.37602307e+00],
        [ 4.14544896e+00, -7.94427611e-01,  2.34920001e+00, ...,
         -2.90737330e+00, -5.61686079e+00, -7.80745982e+00],
        [ 7.75071264e+00,  1.94663028e+00, -1.20939969e+00, ...,
         -3.99846897e+00, -5.85893877e+00, -5.94541405e+00],
        ...,
        [-7.03956529e+00, -1.09246141e+01, -1.22859907e+01, ...,
          1.47647925e+01,  1.05887181e+01,  1.21205781e+01],
        [-2.07348656e+00, -5.91328897e+00, -8.64423635e+00, ...,
          1.25590337e+01,  9.35502329e+00,  9.82700277e+00],
        [-5.03784256e+00, -5.73751503e+00, -8.75455366e+00, ...,
          1.29967212e+01,  1.02247234e+01,  8.69885723e+00]],

       [[-1.41976822e+01, -9.21751853e+00, -3.25265590e+00, ...,
         -5.96497699e+00, -5.17111895e+00, -4.71135896e+00],
        [-1.32392620e+01, -8.33137900e+00, -1.32934869e+00, ...,
         -6.80346715e+00, -5.00460652e+00, -4.00642663e+00],
        [-1.29560231e+01, -6.57265929e+00,  4.32026421e-01, ...,
         -2.81103538e-01, -1.84378955e+00, -2.75801193e+00],
        ...,
        [-8.14339086e+00, -2.01137709e+00,  1.41707031e+00, ...,
          2.32771403e+00,  2.05644990e+00,  2.20897934e+00],
        [-1.16006318e+01, -5.11586887e+00, -1.13186497e+00, ...,
         -1.07483822e+00,  9.77753024e-01, -4.13079411e-02],
        [-1.14733549e+01, -6.20907504e+00, -9.35737413e-01, ...,
         -2.80517632e+00,  4.71894748e-01,  2.67718000e-01]],

       ...,

       [[ 1.04622933e+01,  1.18923617e+01,  1.44945341e+01, ...,
         -9.06546695e+00, -7.66058301e+00, -6.76023946e+00],
        [ 1.55674322e+01,  1.68826873e+01,  1.82920011e+01, ...,
         -1.19907815e+01, -1.25935483e+01, -8.55167506e+00],
        [ 5.60241832e+00,  5.82555418e+00,  6.72208235e+00, ...,
         -3.76862970e+00, -4.55091222e+00, -5.99839635e+00],
        ...,
        [ 7.03607106e-01, -3.13193792e-01, -2.79633410e+00, ...,
          2.18366846e+00, -6.78955651e-01, -1.21561584e+00],
        [ 4.54410192e+00,  3.87902314e+00,  2.80911668e+00, ...,
         -5.60866470e-01, -1.15395115e+00, -4.59980045e-02],
        [-3.44608107e-01, -6.10163763e-01,  2.36424345e-01, ...,
         -1.32035689e+00, -1.27834651e+00, -3.93628333e-01]],

       [[-3.12505298e+00, -6.40706560e-01,  1.44206574e+00, ...,
          7.10477226e+00,  1.47892808e+00, -8.53822616e+00],
        [-3.06040278e+00,  1.92399788e+00, -2.94058081e-01, ...,
         -7.64146898e+00, -4.60261658e+00, -2.82839062e+00],
        [ 1.25203934e+01,  1.24705466e+01,  5.93333257e+00, ...,
          1.32828897e+01,  8.06569950e+00, -1.47448555e+01],
        ...,
        [-1.22293122e+00, -1.72582444e+00,  1.42027132e+00, ...,
          1.06657397e+01,  3.74729322e+00, -1.53451829e+00],
        [-2.91921396e+00, -1.89188537e+00,  9.85753990e-01, ...,
          1.02018221e+01,  8.25287159e+00,  3.78683934e+00],
        [-6.23672151e-01, -6.40457256e-01,  8.02249927e-01, ...,
          6.81585570e+00,  5.19124876e+00,  1.81584282e+00]],

       [[-1.37346924e+01, -1.06854039e+01, -1.03333885e+01, ...,
          5.80505847e+00,  7.14297821e+00,  5.36574544e+00],
        [-7.88593921e+00, -7.71029456e+00, -5.24597618e+00, ...,
          2.77044003e+00,  7.75241659e-01, -2.34010414e+00],
        [-1.01372006e+01, -7.77213876e+00, -5.07525333e+00, ...,
          8.98354267e+00,  9.88822045e+00,  1.01451267e+01],
        ...,
        [-4.22640312e+00, -2.62188023e+00, -5.65680421e+00, ...,
          9.23831448e-01,  1.64407891e+00,  2.46854127e+00],
        [-1.73010736e+00, -1.05555258e+00, -4.33872187e+00, ...,
          1.34110994e+00,  1.56584381e+00,  1.67926918e+00],
        [-2.06108394e-01,  1.26965479e-02, -2.08229856e+00, ...,
         -1.33826170e+00, -3.01095466e-01,  4.12523082e-01]]]), 'subindex': array([[ 1],
       [ 1],
       [ 1],
       ...,
       [11],
       [11],
       [11]], dtype=uint8), 'substate': array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=uint8)}

# Exploratory Data Analysis

In [4]:
# Inspecting the keys and structure of the loaded data
mat_data.keys(), {key: type(mat_data[key]) for key in mat_data.keys()}

(dict_keys(['__header__', '__version__', '__globals__', 'EEGsample', 'subindex', 'substate']),
 {'__header__': bytes,
  '__version__': str,
  '__globals__': list,
  'EEGsample': numpy.ndarray,
  'subindex': numpy.ndarray,
  'substate': numpy.ndarray})

<div style="background-color: #cce5ff; padding: 10px; border: 1px solid #0066cc;">
    <h2 style="color: #0066cc; font-weight: bold;">Assigning Variables</h2>
    
</div>

In [5]:
eeg_samples = mat_data['EEGsample']
subindex = mat_data['subindex']
substates = mat_data['substate']

### Calculate the duration of each sample in seconds

EEGsample" contains 2022 EEG samples of size 20x384 from 11 subjects. Each sample is a 3s EEG data with 128Hz from 30 EEG channels. "subindex" is an array of 2022x1. It contains the subject indexes from 1-11 corresponding to each EEG sample. "substate" is an array of 2022x1. It contains the labels of the samples. 0 corresponds to the alert state and 1 correspond to the drowsy state.

In [6]:
# Calculate the duration of each sample in seconds
sampling_rate = 128  # Hz

num_samples, num_channels, num_time_points = eeg_samples.shape
sample_duration = num_time_points / sampling_rate

### Check for missing values

In [7]:
missing_values = np.isnan(eeg_samples).sum()
if missing_values == 0:
    print("No missing values in the EEG data.")
else:
    print("Number of missing values:", missing_values)

No missing values in the EEG data.

In [8]:
print("Number of subjects:", len(np.unique(subindex)))
print("EEGsample shape:", eeg_samples.shape)
print("Number of Samples:", num_samples)
print("Number of Channels:", num_channels)
print("Number of Time Points:", num_time_points)
print("Sample Duration (seconds):", sample_duration)

unique_labels, label_counts = np.unique(substates, return_counts=True)
print("Unique labels:", unique_labels)
print("Label counts:", label_counts)

Number of subjects: 11
EEGsample shape: (2022, 30, 384)
Number of Samples: 2022
Number of Channels: 30
Number of Time Points: 384
Sample Duration (seconds): 3.0
Unique labels: [0 1]
Label counts: [1011 1011]

#### The initial exploration of the EEG dataset reveals the following details:

#### EEG Samples (EEGsample):

  * The dataset contains 2022 EEG samples.
  * Each EEG sample is from 30 channels.
  * Each channel has 384 data points, corresponding to a 3-second EEG recording at a sampling rate of 128Hz.

#### Subject States (substate):

  * There are two unique states: 0 representing the alert state and 1 representing the drowsy state.
  * Each state has 1011 samples, indicating a balanced dataset with respect to the two states.

#### Subject Indexes (subindex):

  * There are 11 unique subjects in the dataset (labeled 1 to 11).
  * The distribution of samples across subjects varies, ranging from a minimum of 102 samples to a maximum of 314 samples per subject.

## State-specific Analysis: 'Alert' and 'Drowsy'

In [9]:
substates_flat = substates.flatten()

In [10]:
# Calculating means and standard deviations for each channel in both states

#Alert States
mean_alert = np.mean(eeg_samples[substates_flat == 0], axis=(0, 2))
std_alert = np.std(eeg_samples[substates_flat == 0], axis=(0, 2))

#Drowsy States
mean_drowsy = np.mean(eeg_samples[substates_flat == 1], axis=(0, 2))
std_drowsy = np.std(eeg_samples[substates_flat == 1], axis=(0, 2))

In [11]:
# Creating a DataFrame
stats_df = pd.DataFrame({
    'Channel': range(1, 31),
    'Mean_Alert': mean_alert,
    'Std_Alert': std_alert,
    'Mean_Drowsy': mean_drowsy,
    'Std_Drowsy': std_drowsy
})

In [12]:
stats_df

    Channel  Mean_Alert  Std_Alert  Mean_Drowsy  Std_Drowsy
0         1    0.120450  17.630071    -0.163686   10.802148
1         2    0.082160  17.209800    -0.163763   12.170468
2         3    0.052289   9.635932    -0.061430    9.706984
3         4    0.002035  30.798487    -0.113082   11.617223
4         5    0.022715   9.642534    -0.159155   11.707889
5         6    0.021788  26.476227    -0.154311   17.197473
6         7    0.019232  12.678096    -0.126242    9.635353
7         8    0.046900   8.752803    -0.070030    9.094665
8         9    0.023307   9.758593    -0.130595   11.230886
9        10    0.017935   9.891951    -0.138523   12.140691
10       11    0.026675  10.078026    -0.140926   11.493215
11       12    0.025204   9.419806    -0.115374    9.258657
12       13    0.030227   8.676220     0.289249  125.220203
13       14   -0.003453   9.422395    -0.105336   10.629389
14       15    0.020169   9.812209    -0.135267   11.993222
15       16    0.006739   9.497671    -0.118931   10.848385
16       17    0.019268   9.657509    -0.100339   13.435700
17       18    0.017605   8.470344    -0.022570   24.811520
18       19   -0.004788   9.078733    -0.100146   10.261368
19       20    0.019624   9.308660    -0.128844   11.225245
20       21   -0.007867   9.224565    -0.103152   10.433308
21       22    0.021766   8.139648    -0.056785    7.689594
22       23    0.007225   7.684455    -0.060255    8.109360
23       24   -0.003592   8.780666    -0.096036    9.909463
24       25    0.019598   9.051293    -0.118028   10.804096
25       26    0.010883   8.877545    -0.107124    9.976398
26       27    0.033979   7.612370    -0.062159    8.179160
27       28    0.010209   8.213521    -0.026352   10.028616
28       29   -0.011278   8.012658    -0.017755    9.505379
29       30    0.016158   8.402189    -0.030039    9.875275

## EEG Channel Statistics Across Subjects and Timepoints

In [13]:
# Compute basic statistics for each EEG channel
mean_values = np.mean(eeg_samples, axis=(0, 2))  # Compute mean along subjects and timepoints
std_values = np.std(eeg_samples, axis=(0, 2))    # Compute standard deviation along subjects and timepoints
min_values = np.min(eeg_samples, axis=(0, 2))    # Compute minimum along subjects and timepoints
max_values = np.max(eeg_samples, axis=(0, 2))    # Compute maximum along subjects and timepoints

# Create a list of dictionaries for each channel's statistics
channel_stats = [
    {
        "Channel": channel_index + 1,
        "Mean": f"{mean_values[channel_index]:.4f}",
        "Std Dev": f"{std_values[channel_index]:.4f}",
        "Min": f"{min_values[channel_index]:.4f}",
        "Max": f"{max_values[channel_index]:.4f}"
    }
    for channel_index in range(num_channels)
]

In [14]:
# Printing the table
print("Basic Statistics for EEG Channels")
print(tabulate(channel_stats, headers="keys", tablefmt="grid"))

Basic Statistics for EEG Channels
+-----------+---------+-----------+-----------+----------+
|   Channel |    Mean |   Std Dev |       Min |      Max |
+===========+=========+===========+===========+==========+
|         1 | -0.0216 |   14.621  |  -573.236 |  871.908 |
+-----------+---------+-----------+-----------+----------+
|         2 | -0.0408 |   14.9052 | -1299.32  |  911.153 |
+-----------+---------+-----------+-----------+----------+
|         3 | -0.0046 |    9.6717 |  -208.161 |  243.286 |
+-----------+---------+-----------+-----------+----------+
|         4 | -0.0555 |   23.2757 | -1302.31  | 1795.54  |
+-----------+---------+-----------+-----------+----------+
|         5 | -0.0682 |   10.7254 |  -259.186 |  157.868 |
+-----------+---------+-----------+-----------+----------+
|         6 | -0.0663 |   22.3244 | -1914.6   | 1294.24  |
+-----------+---------+-----------+-----------+----------+
|         7 | -0.0535 |   11.2602 |  -496.507 |  754.21  |
+-----------+---------+-----------+-----------+----------+
|         8 | -0.0116 |    8.9256 |  -257.126 |  178.263 |
+-----------+---------+-----------+-----------+----------+
|         9 | -0.0536 |   10.5208 |  -264.446 |  358.262 |
+-----------+---------+-----------+-----------+----------+
|        10 | -0.0603 |   11.0738 |  -170.11  |  172.712 |
+-----------+---------+-----------+-----------+----------+
|        11 | -0.0571 |   10.8091 |  -220.874 |  281.422 |
+-----------+---------+-----------+-----------+----------+
|        12 | -0.0451 |    9.3398 |  -249.349 |  203.987 |
+-----------+---------+-----------+-----------+----------+
|        13 |  0.1597 |   88.7564 | -3195.43  | 3430.91  |
+-----------+---------+-----------+-----------+----------+
|        14 | -0.0544 |   10.0442 |  -259.922 |  369.902 |
+-----------+---------+-----------+-----------+----------+
|        15 | -0.0575 |   10.9574 |  -166.841 |  181.824 |
+-----------+---------+-----------+-----------+----------+
|        16 | -0.0561 |   10.1956 |  -219.692 |  257.303 |
+-----------+---------+-----------+-----------+----------+
|        17 | -0.0405 |   11.7003 |  -423.928 |  333.974 |
+-----------+---------+-----------+-----------+----------+
|        18 | -0.0025 |   18.5386 |  -724.467 | 1960.03  |
+-----------+---------+-----------+-----------+----------+
|        19 | -0.0525 |    9.6882 |  -217.814 |  291.793 |
+-----------+---------+-----------+-----------+----------+
|        20 | -0.0546 |   10.3118 |  -164.804 |  176.846 |
+-----------+---------+-----------+-----------+----------+
|        21 | -0.0555 |    9.8476 |  -168.964 |  227.467 |
+-----------+---------+-----------+-----------+----------+
|        22 | -0.0175 |    7.9179 |  -412.437 |  169.198 |
+-----------+---------+-----------+-----------+----------+
|        23 | -0.0265 |    7.8998 |  -164.085 |  221.974 |
+-----------+---------+-----------+-----------+----------+
|        24 | -0.0498 |    9.3622 |  -182.131 |  228.133 |
+-----------+---------+-----------+-----------+----------+
|        25 | -0.0492 |    9.9665 |  -160.505 |  167.532 |
+-----------+---------+-----------+-----------+----------+
|        26 | -0.0481 |    9.4432 |  -188.102 |  191.192 |
+-----------+---------+-----------+-----------+----------+
|        27 | -0.0141 |    7.901  |  -300.203 |  159.28  |
+-----------+---------+-----------+-----------+----------+
|        28 | -0.0081 |    9.1661 |  -155.317 |  179.167 |
+-----------+---------+-----------+-----------+----------+
|        29 | -0.0145 |    8.7908 |  -164.68  |  149.156 |
+-----------+---------+-----------+-----------+----------+
|        30 | -0.0069 |    9.1684 |  -170.631 |  149.996 |
+-----------+---------+-----------+-----------+----------+

<div style="background-color: #cce5ff; padding: 10px; border: 1px solid #0066cc;">
    <h2 style="color: #0066cc; font-weight: bold;">Data Manipulation</h2>
    
</div>

# Segregating the data into alert and drowsy states

In [15]:
import scipy.io

In [16]:
eeg_samples = mat_data['EEGsample']
subindex = mat_data['subindex']
substates = mat_data['substate']

In [17]:
# Segregate the data into alert and drowsy states
alert_data = mat_data['EEGsample'][mat_data['substate'][:, 0] == 0, :]
drowsy_data = mat_data['EEGsample'][mat_data['substate'][:, 0] == 1, :]

In [18]:
# Save the segregated data as new datasets
scipy.io.savemat('alert_data.mat', {'EEGsample': alert_data})
scipy.io.savemat('drowsy_data.mat', {'EEGsample': drowsy_data})

<div style="background-color: #cce5ff; padding: 10px; border: 1px solid #0066cc;">
    <h2 style="color: #0066cc; font-weight: bold;">Assigning EEG Labels</h2>
    
</div>

In [19]:
labels = ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCZ', 'FC4', 'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'PZ', 'P4', 'T6', 'O1', 'Oz', 'O2']

# Data Manipulation - Alert State

In [20]:
# Load the alert data
alert_data = scipy.io.loadmat('alert_data.mat')

# Transpose the EEGsample for each sample
transposed_alert_data = np.transpose(alert_data['EEGsample'], (0, 2, 1))

transposed_alert_data.shape

(1011, 384, 30)

In [21]:
# Concatenate all the samples together
Manipulated_Alert_Data = np.concatenate(transposed_alert_data, axis=0)

Manipulated_Alert_Data.shape

(388224, 30)

In [22]:
# Create a new dataframe with the concatenated EEG values
Manipulated_Alert_Data = pd.DataFrame(Manipulated_Alert_Data)

### Assigning Labels

In [23]:
Manipulated_Alert_Data.columns = labels

Manipulated_Alert_Data['substate'] = 0

In [24]:
Manipulated_Alert_Data_shape = Manipulated_Alert_Data.shape
print(Manipulated_Alert_Data_shape)

(388224, 31)

In [25]:
Manipulated_Alert_Data

,Fp1,Fp2,F7,F3,Fz,F4,F8,FT7,FC3,FCZ,...,TP8,T5,P3,PZ,P4,T6,O1,Oz,O2,substate
0,4.080976,3.786023,8.346804,6.719097,8.357521,8.916676,6.862104,9.614278,8.955653,11.076102,...,4.477457,1.590643,8.856600,6.898189,3.846108,1.618809,1.528848,-1.199498,1.594009,0
1,5.363737,6.188060,8.691601,6.594982,7.950093,8.835506,7.987136,8.394441,7.126653,8.356511,...,2.415757,1.918520,7.423708,3.755487,1.427838,-0.657721,0.793796,-1.544962,1.900514,0
2,2.168923,1.727106,-0.010906,10.583628,2.440252,1.746089,1.159202,-1.002561,7.059705,1.720240,...,-4.692833,4.261903,3.151329,-1.637562,-5.816451,-8.913891,-1.451266,-4.319859,-4.644263,0
3,6.682761,4.633752,2.093427,16.253235,6.105603,3.943814,4.016592,2.393903,17.343024,6.441727,...,0.839859,2.543160,7.499411,4.182199,-0.059025,-0.736035,4.434387,3.438641,1.207515,0
4,9.795314,8.723788,10.936554,8.182007,8.306618,7.103265,7.980278,12.270826,9.309045,6.750704,...,2.970653,-0.216052,5.413562,5.600711,2.837383,4.172009,0.202442,1.743480,3.413565,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388219,8.233965,0.275736,6.446871,5.908036,9.747110,11.439683,-1.685268,5.394103,5.898229,12.230832,...,-6.909897,-8.072416,-0.579174,5.365872,-2.507618,-7.071795,-5.722929,2.618950,-3.075700,0
388220,7.406664,9.878674,-3.062066,9.699165,12.825886,16.227294,11.658202,0.792909,8.312962,14.986136,...,-4.750323,-9.749710,0.661105,7.605404,0.084582,-4.264237,-3.538781,3.539202,-0.909379,0
388221,13.849187,15.022659,-0.428879,12.096121,18.726862,20.367732,21.341497,-0.920176,11.466241,19.145924,...,2.819010,-14.607244,1.367658,10.402462,6.190984,3.495143,-5.398682,3.006524,-0.195928,0
388222,16.960690,11.183629,8.472685,8.712444,17.208050,19.493375,19.953374,2.115628,10.656352,18.752221,...,9.265103,-15.256238,-1.057022,8.016603,8.461495,8.418237,-9.056400,0.705703,-0.641096,0
388223,6.120572,0.036418,4.256910,10.888335,13.246690,23.589833,10.331308,-1.348828,9.539433,14.732780,...,10.627132,-12.477297,-5.111024,2.032405,3.446180,9.829986,-12.673040,-3.879452,-3.535439,0

In [26]:
Manipulated_Alert_Data.describe()

,Fp1,Fp2,F7,F3,Fz,F4,F8,FT7,FC3,FCZ,...,TP8,T5,P3,PZ,P4,T6,O1,Oz,O2,substate
count,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,...,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.000000,388224.0
mean,0.120450,0.082160,0.052289,0.002035,0.022715,0.021788,0.019232,0.046900,0.023307,0.017935,...,0.021766,0.007225,-0.003592,0.019598,0.010883,0.033979,0.010209,-0.011278,0.016158,0.0
std,17.630093,17.209822,9.635944,30.798527,9.642547,26.476261,12.678112,8.752815,9.758606,9.891964,...,8.139659,7.684464,8.780677,9.051305,8.877557,7.612380,8.213531,8.012668,8.402200,0.0
min,-573.236473,-1299.322323,-179.743368,-1302.310821,-259.186417,-1914.601674,-496.506648,-257.126168,-264.446044,-170.110365,...,-412.436568,-164.084974,-182.130863,-160.504457,-188.102204,-300.202835,-155.316775,-164.679904,-170.630668,0.0
25%,-4.776408,-5.200087,-4.309381,-5.210375,-5.136774,-5.298737,-4.533854,-3.814357,-5.077397,-5.446187,...,-3.618430,-3.631967,-4.483550,-4.728144,-4.541708,-3.618739,-3.935085,-3.812024,-3.973197,0.0
50%,-0.075639,-0.078809,0.021210,-0.007062,-0.025080,-0.004596,0.032909,0.000847,0.002038,-0.015818,...,0.072676,0.064908,0.021311,0.014776,0.011861,0.067332,0.070167,0.027562,0.061650,0.0
75%,4.674139,5.061314,4.318260,5.122598,5.058932,5.269095,4.578348,3.898470,5.029046,5.397253,...,3.720945,3.728646,4.505347,4.764787,4.597949,3.740409,4.070610,3.884409,4.121255,0.0
max,871.907755,911.153120,243.285973,1795.543933,157.868435,1116.638265,754.210204,178.262784,358.262495,172.711611,...,169.197791,221.973860,228.132948,167.531582,191.191891,159.280290,153.842957,148.846683,146.055474,0.0

# Data Manipulation - Drowsy State

In [27]:
# Load the alert data
drowsy_data = scipy.io.loadmat('drowsy_data.mat')

# Transpose the EEGsample for each sample
transposed_drowsy_data = np.transpose(drowsy_data['EEGsample'], (0, 2, 1))

transposed_drowsy_data.shape

(1011, 384, 30)

In [28]:
# Concatenate all the samples together
Manipulated_drowsy_data = np.concatenate(transposed_drowsy_data, axis=0)

Manipulated_drowsy_data.shape

(388224, 30)

In [29]:
# Create a new dataframe with the concatenated EEG values
Manipulated_drowsy_data = pd.DataFrame(Manipulated_drowsy_data)

### Assigning Labels

In [30]:
Manipulated_drowsy_data.columns = labels

Manipulated_drowsy_data['substate'] = 1

In [31]:
Manipulated_drowsy_data

,Fp1,Fp2,F7,F3,Fz,F4,F8,FT7,FC3,FCZ,...,TP8,T5,P3,PZ,P4,T6,O1,Oz,O2,substate
0,-9.340455,-2.581835,0.605112,-1.951353,-1.691814,0.000079,3.330641,-0.191926,-4.416670,-1.147983,...,2.129284,-3.047745,-4.376038,-3.188374,-0.385878,1.875040,-5.343100,-3.923701,-2.074438,1
1,-9.297278,1.208397,1.506896,-2.264259,-0.276102,2.584222,6.163738,1.151379,-4.483509,0.162938,...,5.101435,-6.010214,-4.166642,-2.759660,1.960440,2.900005,-5.235632,-4.409118,-0.922046,1
2,-5.377346,4.373476,1.989039,0.960820,4.204186,7.833417,6.751105,1.460457,-1.914790,4.162968,...,4.944842,-5.937366,-2.171945,1.778525,4.798910,3.802374,-4.404817,-2.675341,1.579044,1
3,-0.387827,6.691171,5.519700,7.556678,9.908533,9.829516,7.316607,5.024432,4.905958,11.028363,...,7.509409,-2.738498,3.898276,9.131125,11.175130,7.386306,-0.541670,2.996915,6.289799,1
4,4.371176,8.625327,7.997311,13.974010,13.865399,12.207135,6.853086,7.709539,11.165707,16.520067,...,9.410449,0.360403,9.101561,13.200414,15.277298,6.949633,-0.142043,4.255927,8.020452,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388219,6.868306,2.037630,10.935329,3.053171,2.061508,-2.051896,-6.980084,6.915801,1.292861,-2.156677,...,0.466622,1.703162,0.489967,-0.037224,-1.715912,1.355944,0.816035,0.522263,-0.399985,1
388220,3.248673,-3.479991,8.520732,-0.933774,-2.160580,-5.932663,-12.832424,4.543766,-2.418177,-6.189452,...,-1.080016,2.258167,-0.767202,-2.633476,-5.121715,-0.736463,0.412399,-0.159130,-2.200928,1
388221,5.805058,2.770440,8.983543,1.738981,-0.541900,-8.541175,-8.517280,3.491680,-1.389771,-5.822860,...,-3.365152,3.624552,0.280940,-3.084484,-4.691478,-3.197477,0.923831,1.341110,-1.338262,1
388222,7.142978,0.775242,9.888220,4.223264,0.790337,-6.479811,-12.121178,4.921120,0.083320,-4.330250,...,-2.798542,4.248466,1.042023,-2.643634,-3.409195,-2.482608,1.644079,1.565844,-0.301095,1
388223,5.365745,-2.340104,10.145127,3.204299,0.128407,-4.656551,-13.939822,9.154483,1.264282,-3.263205,...,-2.442473,4.421849,3.490519,-0.725364,-2.018021,-1.486724,2.468541,1.679269,0.412523,1

# Creating new Manipulated EEG Data

In [32]:
# Concatenate them row-wise
Manipulated_EEG_Data = pd.concat([Manipulated_Alert_Data, Manipulated_drowsy_data], ignore_index=True)

Manipulated_EEG_Data = pd.DataFrame(Manipulated_EEG_Data)

Manipulated_EEG_Data

,Fp1,Fp2,F7,F3,Fz,F4,F8,FT7,FC3,FCZ,...,TP8,T5,P3,PZ,P4,T6,O1,Oz,O2,substate
0,4.080976,3.786023,8.346804,6.719097,8.357521,8.916676,6.862104,9.614278,8.955653,11.076102,...,4.477457,1.590643,8.856600,6.898189,3.846108,1.618809,1.528848,-1.199498,1.594009,0
1,5.363737,6.188060,8.691601,6.594982,7.950093,8.835506,7.987136,8.394441,7.126653,8.356511,...,2.415757,1.918520,7.423708,3.755487,1.427838,-0.657721,0.793796,-1.544962,1.900514,0
2,2.168923,1.727106,-0.010906,10.583628,2.440252,1.746089,1.159202,-1.002561,7.059705,1.720240,...,-4.692833,4.261903,3.151329,-1.637562,-5.816451,-8.913891,-1.451266,-4.319859,-4.644263,0
3,6.682761,4.633752,2.093427,16.253235,6.105603,3.943814,4.016592,2.393903,17.343024,6.441727,...,0.839859,2.543160,7.499411,4.182199,-0.059025,-0.736035,4.434387,3.438641,1.207515,0
4,9.795314,8.723788,10.936554,8.182007,8.306618,7.103265,7.980278,12.270826,9.309045,6.750704,...,2.970653,-0.216052,5.413562,5.600711,2.837383,4.172009,0.202442,1.743480,3.413565,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776443,6.868306,2.037630,10.935329,3.053171,2.061508,-2.051896,-6.980084,6.915801,1.292861,-2.156677,...,0.466622,1.703162,0.489967,-0.037224,-1.715912,1.355944,0.816035,0.522263,-0.399985,1
776444,3.248673,-3.479991,8.520732,-0.933774,-2.160580,-5.932663,-12.832424,4.543766,-2.418177,-6.189452,...,-1.080016,2.258167,-0.767202,-2.633476,-5.121715,-0.736463,0.412399,-0.159130,-2.200928,1
776445,5.805058,2.770440,8.983543,1.738981,-0.541900,-8.541175,-8.517280,3.491680,-1.389771,-5.822860,...,-3.365152,3.624552,0.280940,-3.084484,-4.691478,-3.197477,0.923831,1.341110,-1.338262,1
776446,7.142978,0.775242,9.888220,4.223264,0.790337,-6.479811,-12.121178,4.921120,0.083320,-4.330250,...,-2.798542,4.248466,1.042023,-2.643634,-3.409195,-2.482608,1.644079,1.565844,-0.301095,1
776447,5.365745,-2.340104,10.145127,3.204299,0.128407,-4.656551,-13.939822,9.154483,1.264282,-3.263205,...,-2.442473,4.421849,3.490519,-0.725364,-2.018021,-1.486724,2.468541,1.679269,0.412523,1

In [33]:
Manipulated_EEG_Data.describe()

,Fp1,Fp2,F7,F3,Fz,F4,F8,FT7,FC3,FCZ,...,TP8,T5,P3,PZ,P4,T6,O1,Oz,O2,substate
count,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,...,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.000000,776448.0
mean,-0.021618,-0.040802,-0.004570,-0.055523,-0.068220,-0.066261,-0.053505,-0.011565,-0.053644,-0.060294,...,-0.017509,-0.026515,-0.049814,-0.049215,-0.048120,-0.014090,-0.008072,-0.014516,-0.006941,0.5
std,14.620990,14.905172,9.671696,23.275682,10.725436,22.324431,11.260219,8.925568,10.520814,11.073835,...,7.917922,7.899842,9.362213,9.966547,9.443160,7.901001,9.166132,8.790766,9.168400,0.5
min,-573.236473,-1299.322323,-208.160484,-1302.310821,-259.186417,-1914.601674,-496.506648,-257.126168,-264.446044,-170.110365,...,-412.436568,-164.084974,-182.130863,-160.504457,-188.102204,-300.202835,-155.316775,-164.679904,-170.630668,0.0
25%,-5.350544,-5.673096,-4.867582,-5.980532,-6.031645,-6.040908,-5.034842,-4.501781,-5.895260,-6.349755,...,-3.989990,-4.059459,-5.113621,-5.467732,-5.173702,-4.049075,-4.513315,-4.367126,-4.517431,0.0
50%,-0.156583,-0.151739,-0.057676,-0.110664,-0.136852,-0.094769,-0.051081,-0.000729,-0.110086,-0.133952,...,0.042863,0.049731,-0.028798,-0.051791,-0.036366,0.070813,0.095885,0.052832,0.077466,0.5
75%,5.073020,5.396961,4.732961,5.728880,5.750800,5.840688,4.904647,4.418808,5.661637,6.091726,...,4.026763,4.130372,5.037588,5.361387,5.104271,4.161815,4.700240,4.482325,4.689910,1.0
max,871.907755,911.153120,243.285973,1795.543933,157.868435,1294.240965,754.210204,178.262784,358.262495,172.711611,...,169.197791,221.973860,228.132948,167.531582,191.191891,159.280290,179.167203,149.156242,149.996483,1.0

In [34]:
Manipulated_EEG_Data.shape

(776448, 31)

In [35]:
Manipulated_EEG_Data["substate"].value_counts()

substate
0    388224
1    388224
Name: count, dtype: int64

# Shuffle Dataset

In [36]:
from sklearn.utils import shuffle

# Shuffle the combined dataset
shuffled_data = shuffle(Manipulated_EEG_Data, random_state=42)

# Display the resulting shuffled DataFrame
print(Manipulated_EEG_Data.head())

        Fp1       Fp2         F7         F3        Fz        F4        F8  \
0  4.080976  3.786023   8.346804   6.719097  8.357521  8.916676  6.862104
1  5.363737  6.188060   8.691601   6.594982  7.950093  8.835506  7.987136
2  2.168923  1.727106  -0.010906  10.583628  2.440252  1.746089  1.159202
3  6.682761  4.633752   2.093427  16.253235  6.105603  3.943814  4.016592
4  9.795314  8.723788  10.936554   8.182007  8.306618  7.103265  7.980278

         FT7        FC3        FCZ  ...       TP8        T5        P3  \
0   9.614278   8.955653  11.076102  ...  4.477457  1.590643  8.856600
1   8.394441   7.126653   8.356511  ...  2.415757  1.918520  7.423708
2  -1.002561   7.059705   1.720240  ... -4.692833  4.261903  3.151329
3   2.393903  17.343024   6.441727  ...  0.839859  2.543160  7.499411
4  12.270826   9.309045   6.750704  ...  2.970653 -0.216052  5.413562

         PZ        P4        T6        O1        Oz        O2  substate
0  6.898189  3.846108  1.618809  1.528848 -1.199498  1.594009         0
1  3.755487  1.427838 -0.657721  0.793796 -1.544962  1.900514         0
2 -1.637562 -5.816451 -8.913891 -1.451266 -4.319859 -4.644263         0
3  4.182199 -0.059025 -0.736035  4.434387  3.438641  1.207515         0
4  5.600711  2.837383  4.172009  0.202442  1.743480  3.413565         0

[5 rows x 31 columns]

# Manual Feature Selection

In [37]:
Manipulated_EEG_Data.columns

Index(['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCZ', 'FC4',
       'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8',
       'T5', 'P3', 'PZ', 'P4', 'T6', 'O1', 'Oz', 'O2', 'substate'],
      dtype='object')

In [38]:
# Define the feature sets
feature_sets = {
    "df_5": ["FC3", "Fz", "F7", "FT7", "T4"],
    "df_8": ["FC3", "Fz", "F7", "FT7", "T4", "T3", "Fp2", "Fp1"],
    "df_16": ["FC3", "Fz", "F7", "FT7", "T4", "T3", "Fp2", "Fp1", "TP7", "CP3", "F4", "F8", "F3", "O2", "O1", "T6"],
    "df_22": ["FC3", "Fz", "F7", "FT7", "T4", "T3", "Fp2", "Fp1", "TP7", "CP3", "F4", "F8", "F3", "O2", "O1", "T6", "Oz", "FT8", "PZ", "T5", "FCZ", "C4"],
    "df_30": ["FC3", "Fz", "F7", "FT7", "T4", "T3", "Fp2", "Fp1", "TP7", "CP3", "F4", "F8", "F3", "O2", "O1", "T6", "Oz", "FT8", "PZ", "T5", "FCZ", "C4", "CP4", "TP8", "FC4", "C3", "P3", "CPz", "P4", "Cz"]
}

# Initialize new DataFrames with their respective features and 'substate' column as target
df_5 = Manipulated_EEG_Data[feature_sets["df_5"] + ["substate"]]
df_8 = Manipulated_EEG_Data[feature_sets["df_8"] + ["substate"]]
df_16 = Manipulated_EEG_Data[feature_sets["df_16"] + ["substate"]]
df_22 = Manipulated_EEG_Data[feature_sets["df_22"] + ["substate"]]
df_30 = Manipulated_EEG_Data[feature_sets["df_30"] + ["substate"]]

# Display the first few rows of each DataFrame to verify
print(df_5.head())
print(df_8.head())
print(df_16.head())
print(df_22.head())
print(df_30.head())

         FC3        Fz         F7        FT7        T4  substate
0   8.955653  8.357521   8.346804   9.614278  5.239404         0
1   7.126653  7.950093   8.691601   8.394441  4.168537         0
2   7.059705  2.440252  -0.010906  -1.002561 -3.846026         0
3  17.343024  6.105603   2.093427   2.393903  0.233709         0
4   9.309045  8.306618  10.936554  12.270826  2.806923         0
         FC3        Fz         F7        FT7        T4         T3       Fp2  \
0   8.955653  8.357521   8.346804   9.614278  5.239404   9.273010  3.786023
1   7.126653  7.950093   8.691601   8.394441  4.168537   9.211276  6.188060
2   7.059705  2.440252  -0.010906  -1.002561 -3.846026  -0.533738  1.727106
3  17.343024  6.105603   2.093427   2.393903  0.233709   0.904006  4.633752
4   9.309045  8.306618  10.936554  12.270826  2.806923  10.492772  8.723788

        Fp1  substate
0  4.080976         0
1  5.363737         0
2  2.168923         0
3  6.682761         0
4  9.795314         0
         FC3        Fz         F7        FT7        T4         T3       Fp2  \
0   8.955653  8.357521   8.346804   9.614278  5.239404   9.273010  3.786023
1   7.126653  7.950093   8.691601   8.394441  4.168537   9.211276  6.188060
2   7.059705  2.440252  -0.010906  -1.002561 -3.846026  -0.533738  1.727106
3  17.343024  6.105603   2.093427   2.393903  0.233709   0.904006  4.633752
4   9.309045  8.306618  10.936554  12.270826  2.806923  10.492772  8.723788

        Fp1       TP7       CP3        F4        F8         F3        O2  \
0  4.080976 -2.606951  9.031140  8.916676  6.862104   6.719097  1.594009
1  5.363737 -2.471805  6.685597  8.835506  7.987136   6.594982  1.900514
2  2.168923  9.674524  1.989836  1.746089  1.159202  10.583628 -4.644263
3  6.682761  5.164781  8.198399  3.943814  4.016592  16.253235  1.207515
4  9.795314  4.534093  7.414361  7.103265  7.980278   8.182007  3.413565

         O1        T6  substate
0  1.528848  1.618809         0
1  0.793796 -0.657721         0
2 -1.451266 -8.913891         0
3  4.434387 -0.736035         0
4  0.202442  4.172009         0
         FC3        Fz         F7        FT7        T4         T3       Fp2  \
0   8.955653  8.357521   8.346804   9.614278  5.239404   9.273010  3.786023
1   7.126653  7.950093   8.691601   8.394441  4.168537   9.211276  6.188060
2   7.059705  2.440252  -0.010906  -1.002561 -3.846026  -0.533738  1.727106
3  17.343024  6.105603   2.093427   2.393903  0.233709   0.904006  4.633752
4   9.309045  8.306618  10.936554  12.270826  2.806923  10.492772  8.723788

        Fp1       TP7       CP3  ...        O2        O1        T6        Oz  \
0  4.080976 -2.606951  9.031140  ...  1.594009  1.528848  1.618809 -1.199498
1  5.363737 -2.471805  6.685597  ...  1.900514  0.793796 -0.657721 -1.544962
2  2.168923  9.674524  1.989836  ... -4.644263 -1.451266 -8.913891 -4.319859
3  6.682761  5.164781  8.198399  ...  1.207515  4.434387 -0.736035  3.438641
4  9.795314  4.534093  7.414361  ...  3.413565  0.202442  4.172009  1.743480

        FT8        PZ        T5        FCZ        C4  substate
0  9.487663  6.898189  1.590643  11.076102  7.419910         0
1  9.044951  3.755487  1.918520   8.356511  5.555498         0
2  1.343115 -1.637562  4.261903   1.720240 -2.211172         0
3  5.130613  4.182199  2.543160   6.441727  1.990277         0
4  7.993644  5.600711 -0.216052   6.750704  4.534005         0

[5 rows x 23 columns]
         FC3        Fz         F7        FT7        T4         T3       Fp2  \
0   8.955653  8.357521   8.346804   9.614278  5.239404   9.273010  3.786023
1   7.126653  7.950093   8.691601   8.394441  4.168537   9.211276  6.188060
2   7.059705  2.440252  -0.010906  -1.002561 -3.846026  -0.533738  1.727106
3  17.343024  6.105603   2.093427   2.393903  0.233709   0.904006  4.633752
4   9.309045  8.306618  10.936554  12.270826  2.806923  10.492772  8.723788

        Fp1       TP7       CP3  ...        C4       CP4       TP8       FC4  \
0  4.080976 -2.606951  9.031140  ...  7.419910  4.488538  4.477457  8.805747
1  5.363737 -2.471805  6.685597  ...  5.555498  3.023837  2.415757  7.698437
2  2.168923  9.674524  1.989836  ... -2.211172 -4.485516 -4.692833  0.251319
3  6.682761  5.164781  8.198399  ...  1.990277 -0.043161  0.839859  4.052372
4  9.795314  4.534093  7.414361  ...  4.534005  1.963395  2.970653  7.488636

          C3        P3       CPz        P4         Cz  substate
0  12.881575  8.856600  8.092092  3.846108  10.263936         0
1   8.199360  7.423708  6.468148  1.427838   7.948053         0
2   2.909449  3.151329 -0.356659 -5.816451   0.372125         0
3  12.797120  7.499411  4.055606 -0.059025   4.200642         0
4   9.813168  5.413562  5.555350  2.837383   5.911603         0

[5 rows x 31 columns]

In [39]:
from sklearn.model_selection import train_test_split

# Dictionary to store train-test splits for each feature set
splits = {}

# Loop through each feature set
for key in feature_sets:
    # Get the DataFrame with selected features and the target
    df = Manipulated_EEG_Data[feature_sets[key] + ["substate"]]
    
    # Define X and y
    X = df.drop("substate", axis=1)
    y = df["substate"]
    
    # Perform train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Store the splits in the dictionary
    splits[key] = {
        "X_train": X_train,
        "X_test": X_test,
        "y_train": y_train,
        "y_test": y_test
    }

# Display the shapes of the splits to verify
for key in splits:
    print(f"{key} - X_train shape: {splits[key]['X_train'].shape}, X_test shape: {splits[key]['X_test'].shape}")
    print(f"{key} - y_train shape: {splits[key]['y_train'].shape}, y_test shape: {splits[key]['y_test'].shape}")

df_5 - X_train shape: (621158, 5), X_test shape: (155290, 5)
df_5 - y_train shape: (621158,), y_test shape: (155290,)
df_8 - X_train shape: (621158, 8), X_test shape: (155290, 8)
df_8 - y_train shape: (621158,), y_test shape: (155290,)
df_16 - X_train shape: (621158, 16), X_test shape: (155290, 16)
df_16 - y_train shape: (621158,), y_test shape: (155290,)
df_22 - X_train shape: (621158, 22), X_test shape: (155290, 22)
df_22 - y_train shape: (621158,), y_test shape: (155290,)
df_30 - X_train shape: (621158, 30), X_test shape: (155290, 30)
df_30 - y_train shape: (621158,), y_test shape: (155290,)

In [40]:
import numpy as np
import os

# Create folders and save each feature set's train-test split as .npy files
for key in splits:
    # Create a folder for each feature set if it doesn't already exist
    folder_path = f"./{key}"
    os.makedirs(folder_path, exist_ok=True)
    
    # Save the train and test splits as .npy files
    np.save(os.path.join(folder_path, "X_train.npy"), splits[key]["X_train"].values)
    np.save(os.path.join(folder_path, "X_test.npy"), splits[key]["X_test"].values)
    np.save(os.path.join(folder_path, "y_train.npy"), splits[key]["y_train"].values)
    np.save(os.path.join(folder_path, "y_test.npy"), splits[key]["y_test"].values)

    print(f"Saved {key} splits in folder: {folder_path}")

Saved df_5 splits in folder: ./df_5
Saved df_8 splits in folder: ./df_8
Saved df_16 splits in folder: ./df_16
Saved df_22 splits in folder: ./df_22
Saved df_30 splits in folder: ./df_30